version: "3.9"

services:
  balancer:
    build:
      context: .
      dockerfile: ./cmd/balancer/Dockerfile
    volumes:
      - .:/src
    ports:
      - 9090:9090

  backend-1:
    build:
      context: .
      dockerfile: ./cmd/backend/Dockerfile
    environment:
      - SERVNAME=backend-1
    volumes:
      - .:/src

  backend-2:
    build:
      context: .
      dockerfile: ./cmd/backend/Dockerfile
    environment:
      - SERVNAME=backend-2
    volumes:
      - .:/src

  backend-3:
    build:
      context: .
      dockerfile: ./cmd/backend/Dockerfile
    environment:
      - SERVNAME=backend-3
    volumes:
      - .:/src