version: "3.9"

services:
  proxy-server:
    build:
      context: .
      dockerfile: ./cmd/balancer/Dockerfile
    volumes:
      - .:/src
    ports:
      - 9090:9090
    depends_on:
      - backend-1
#      - backend-2
#      - backend-3

  backend-1:
    build:
      context: .
      dockerfile: ./cmd/backend/Dockerfile
    environment:
      - SERVNAME=backend-1
    volumes:
      - .:/src

#  backend-2:
#    build:
#      context: .
#      dockerfile: ./cmd/backend/Dockerfile
#    environment:
#      - SERVNAME=backend-2
#    volumes:
#      - .:/src
#
#  backend-3:
#    build:
#      context: .
#      dockerfile: ./cmd/backend/Dockerfile
#    environment:
#      - SERVNAME=backend-3
#    volumes:
#      - .:/src

#  client-1:
#    build:
#      context: .
#      dockerfile: ./cmd/frontend/Dockerfile
#    volumes:
#      - .:/src
#    depends_on:
#      - proxy-server